// stats.js — inline data, no fetch needed (works with file://)
window.STATS_DATA = [
  {id:"max-health",label:"พลังชีวิตสูงสุด",unit:"flat"},
  {id:"health-regeneration",label:"อัตราฟื้นฟูพลังชีวิต",unit:"flat"},
  {id:"max-mana",label:"มานาสูงสุด",unit:"flat"},
  {id:"mana-regeneration",label:"อัตราฟื้นฟูมานา",unit:"flat"},
  {id:"max-stamina",label:"สตามินาสูงสุด",unit:"flat"},
  {id:"stamina-regeneration",label:"อัตราฟื้นฟูสตามินา",unit:"flat"},
  {id:"attack-damage",label:"พลังโจมตี",unit:"flat"},
  {id:"attack-speed",label:"ความเร็วโจมตี",unit:"flat"},
  {id:"critical-strike-chance",label:"โอกาสคริติคอล",unit:"percent"},
  {id:"critical-strike-power",label:"คริติคอลดาเมจ",unit:"percent"},
  {id:"skill-critical-strike-chance",label:"โอกาสคริติคอล (สกิล)",unit:"percent"},
  {id:"skill-critical-strike-power",label:"คริติคอลดาเมจ (สกิล)",unit:"percent"},
  {id:"physical-damage",label:"ความเสียหายกายภาพ",unit:"percent"},
  {id:"magic-damage",label:"ความเสียหายเวทยมนตร์",unit:"percent"},
  {id:"skill-damage",label:"ความเสียหายสกิล",unit:"percent"},
  {id:"weapon-damage",label:"ความเสียหายอาวุธ",unit:"percent"},
  {id:"projectile-damage",label:"ความเสียหายระยะไกล",unit:"percent"},
  {id:"pve-damage",label:"ความเสียหายต่อมอนส์เตอร์",unit:"percent"},
  {id:"pvp-damage",label:"ความเสียหายต่อผู้เล่น",unit:"percent"},
  {id:"undead-damage",label:"ความเสียหายอันเดธ",unit:"percent"},
  {id:"elemental-damage",label:"ดาเมจธาตุ",unit:"percent"},
  {id:"lifesteal",label:"ดูดเลือด",unit:"percent"},
  {id:"spell-vampirism",label:"ดูดเลือดจากสกิล",unit:"percent"},
  {id:"defense",label:"พลังป้องกัน",unit:"flat"},
  {id:"damage-reduction",label:"ลดความเสียหาย",unit:"percent"},
  {id:"physical-damage-reduction",label:"ลดความเสียหายกายภาพ",unit:"percent"},
  {id:"magic-damage-reduction",label:"ลดความเสียหายเวทย์มนต์",unit:"percent"},
  {id:"projectile-damage-reduction",label:"ลดความเสียหายกระสุน",unit:"percent"},
  {id:"fire-damage-reduction",label:"ลดความเสียหายไฟ",unit:"percent"},
  {id:"fall-damage-reduction",label:"ลดความเสียหายจากการตก",unit:"percent"},
  {id:"pve-damage-reduction",label:"ลดความเสียหายจากมอนส์เตอร์",unit:"percent"},
  {id:"pvp-damage-reduction",label:"ลดความเสียหายจากผู้เล่น",unit:"percent"},
  {id:"block-rating",label:"โอกาสบล็อค",unit:"percent"},
  {id:"block-power",label:"พลังบล็อค",unit:"percent"},
  {id:"block-cooldown-reduction",label:"บล็อคไวขึ้น",unit:"percent"},
  {id:"dodge-rating",label:"โอกาสหลบหลีก",unit:"percent"},
  {id:"dodge-cooldown-reduction",label:"หลบหลีกไวขึ้น",unit:"percent"},
  {id:"parry-rating",label:"โอกาสโต้กลับ",unit:"percent"},
  {id:"parry-cooldown-reduction",label:"โต้กลับไวขึ้น",unit:"percent"},
  {id:"cooldown-reduction",label:"ลดคูลดาวน์สกิล",unit:"percent"},
  {id:"movement-speed",label:"ความเร็วเคลื่อนที่",unit:"flat"}
];
